-- DropEnum
DROP TYPE "public"."crdb_internal_region";

-- CreateTable
CREATE TABLE "Item" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name" STRING NOT NULL,
    "description" STRING,

    CONSTRAINT "Item_pkey" PRIMARY KEY ("id")
);
